In [1]:
# Decision Tree Classification

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.tree import DecisionTreeClassifier

In [7]:
# Importing the dataset
dataset = pd.read_csv('train.csv').as_matrix()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [8]:
print(dataset)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [9]:
classifier = DecisionTreeClassifier()

In [10]:
X_train= dataset[0:21000,1:]

In [16]:
X_train_label=X_train[0:21000,0]

In [17]:
classifier.fit(X_train,X_train_label)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [20]:
#Testing Data
X_test=dataset[21000 : ,1 :]

In [21]:
actual_label = dataset[21000: , 0]

In [36]:
y_pred = classifier.predict(X_test)
count = 0 ;
for i in range(0,21000):
    count+= 1 if y_pred[i] == actual_label[i] else 0
print("Accurecy = ", (count/21000)* 1000)
    


Accurecy =  99.42857142857142
